[env:esp32cam]
platform  = espressif32
board     = esp32cam
framework = espidf

monitor_speed          = 115200
board_upload.flash_size = 4MB
board_build.partitions  = huge_app.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3

; libssh2 wird automatisch über den IDF Component Manager geladen (src/idf_component.yml).
; Kein manueller Schritt nötig.
